In [2]:
import numpy as np

In [ ]:
a = np.zeros(3) # type(a[0]) is float64
a

array([0., 0., 0.])

In [11]:
b = np.ones(5)
b.shape

(5,)

In [ ]:
b.shape = (5, 1)
b

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
z = np.empty(3) # array of uninitialized data
z

array([0., 0., 0.])

In [ ]:
z = np.linspace(0, 1, 5) # creates 5 points between 0 and 1
z

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
y = np.array([3, 2]) # 1D list to 1D array
y

array([3, 2])

In [20]:
a_list = [[1, 2], [3, 4]]
z = np.array(a_list) # creates a 2D array using python list
z

array([[1, 2],
       [3, 4]])

In [ ]:
y = np.arange(0, 10, 2) # array with values from 0 to 10 with a step of 2
y

array([0, 2, 4, 6, 8])

linspace vs arange:

linspace(Start, Stop, Number of values) -> Generates num evenly spaced numbers between start and stop (stop included).

arange(Start, Stop, Step size) -> Generates values in a range using a specified step size.

In [ ]:
x = np.random.randint(1, 7)
x # random integer between 1 and 6

3

numpy.random.randint(low, high=None, size=None, dtype=int)

In [24]:
X = np.random.randint(1, 7, 4) # 4 random integers between 1 and 6
X


array([1, 1, 3, 3], dtype=int32)

Without setting the seed, every time we run our code, we'll get different random values.

In [28]:
np.random.seed(0) # set seed to get same values every time
x = np.random.randint(1, 10, 5)
x

array([6, 1, 4, 4, 8], dtype=int32)

In [32]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])   # using indices
arr[-1]  # last element

10


np.int64(50)

In [30]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d[0, 1]  # Output: 2 (row 0, column 1)

np.int64(2)